---
# tasks file for new-role
- name: create devs group
  group:
    name: devs
    state: present
- name: add user and add to group
  user:
    name: noveed
    group: devs
    state: present
- name: install zsh
  apt:
    name: zsh
    state: present
- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
- name: replace html
  copy:
    src: files/index.html
    dest: /var/www/html/
  notify: restart nginx

- name: install java
  package:
    name:
      - openjdk-17-jre
      - wget
    state: present
    update_cache: yes

- name: download jenkins repo key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
- name: add jenkins repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
- name: install jenkins
  apt:
    name: jenkins
    state: present
- name: start and enable jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
